site :opscode

cookbook 'nginx'
cookbook 'sudo'
cookbook 'apt'
cookbook 'ntp'
cookbook 'redisio'
cookbook 'postgresql', git: 'git@github.com:phlipper/chef-postgresql.git', tag: '0.13.0'
cookbook 'runit'
cookbook 'logrotate'
cookbook 'postfix'
cookbook 'openssh'
cookbook 'hostname'
cookbook 'resolver'
cookbook 'omnibus_updater'
cookbook 'locale'
cookbook 'user', git: 'git@github.com:fnichol/chef-user.git', tag: '0.3.0'
cookbook 'rsyslog'
cookbook 'chef-client'
cookbook 'logwatch'
cookbook 'chef-rbenv', git: 'git@github.com:fnichol/chef-rbenv.git', tag: '0.7.2'
