source 'http://api.berkshelf.com'

cookbook 'nginx'
cookbook 'sudo'
cookbook 'apt', '> 1.9'
cookbook 'ntp'
cookbook 'redis', git: 'https://github.com/phlipper/chef-redis.git'
cookbook 'postgresql', git: 'git@github.com:phlipper/chef-postgresql.git'
cookbook 'runit'
cookbook 'logrotate'
cookbook 'postfix'
cookbook 'openssh'
cookbook 'hostname'
cookbook 'resolver'
cookbook 'omnibus_updater'
cookbook 'locale'
cookbook 'user', git: 'git@github.com:fnichol/chef-user.git'
cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch'
cookbook 'rsyslog'
cookbook 'chef-client'
cookbook 'logwatch'
cookbook 'smartmontools'
cookbook 'sysstat'
cookbook 'chef-vault'
cookbook 'sysctl', git: 'https://github.com/spheromak/sysctl-cookbook.git'
cookbook 'apticron'
cookbook 'chef-sugar'
cookbook 'rsync'
cookbook 'bash-completion'
cookbook 'vim'
cookbook 'git'
cookbook 'tmux'
cookbook 'imagemagick'
cookbook 'tarsnap', git: 'git@github.com:jssjr/chef-tarsnap.git'
cookbook 'fail2ban'
cookbook 'simple_iptables'
cookbook 'annoyances'
cookbook 'sanitize'
cookbook 'motd', git: 'https://github.com/flinc-chef/motd.git'
cookbook 'monit', git: 'https://github.com/phlipper/chef-monit.git'
cookbook 'ulimit', git: 'https://github.com/bmhatfield/chef-ulimit.git'
cookbook 'datadog'
cookbook 'hostsfile'
cookbook 'client-rekey'
cookbook 'ruby_install'

cookbook 'wallgig',
         path: 'site-cookbooks/wallgig'

